Repository meilisearch/meilisearch-rails, pull requests merged in 2022-02, with the labels that each got.

#108 Fix Rails module calls inside the Meilisearch::Rails & Add smoke-test workflow step
  .github/workflows/tests.yml
  bors.toml
  lib/meilisearch/rails/railtie.rb
  lib/meilisearch/rails/tasks/meilisearch.rake
  playground/app/models/book.rb
  playground/config/initializers/meilisearch.rb
  spec/utilities_spec.rb
Labels: bug

#111 Update version for the next release (v0.5.0)
  lib/meilisearch/rails/version.rb
Labels: skip-changelog

#116 Integration test rubies
  .github/workflows/tests.yml
  bors.toml
  lib/meilisearch-rails.rb
Labels: enhancement

#119 Fix Meilisearch naming in the gemspec
  meilisearch-rails.gemspec
Labels: skip-changelog

#122 Fix release version checker
  .github/scripts/check-release.sh
Labels: bug, skip-changelog

#125 fix ms_job loading path
  .github/workflows/tests.yml
  lib/meilisearch-rails.rb
Labels: bug

#127 Update version for the next release (v0.5.1)
  lib/meilisearch/rails/version.rb
Labels: skip-changelog
