Repository meilisearch/meilisearch-rails, pull requests merged in 2022-06, with the labels that each got.

#151 Improve Docker configuration in the package
  .editorconfig
  CONTRIBUTING.md
  docker-compose.yml
Labels: enhancement

#154 Remove camelCase attributes and empty blocks from README
  README.md
Labels: skip-changelog

#153 Enhancement/PerEnvironment configuration
  .rubocop_todo.yml
  README.md
  lib/meilisearch-rails.rb
  spec/integration_spec.rb
  spec/spec_helper.rb
Labels: enhancement, breaking-change

#164 Check for Sequel::Model instead of only ::Sequel
  lib/meilisearch-rails.rb
Labels: bug
