Repository meilisearch/meilisearch-rails, pull requests merged in 2023-11, with the labels that each got.

#292 Remove redundant calls to sleep in tests
  spec/integration_spec.rb
Labels: skip-changelog, maintenance

#307 Add new section to release drafter
  .github/release-draft-template.yml
Labels: skip-changelog

#299 Properly clean up indexes after test suite runs
  spec/spec_helper.rb
  spec/support/2_method_helpers.rb
  spec/support/active_record_classes.rb
Labels: maintenance

#293 Warn when you make missing attribute searchable
  .rubocop_todo.yml
  lib/meilisearch-rails.rb
  lib/meilisearch/rails/pagination.rb
  spec/integration_spec.rb
Labels: enhancement

#296 Make integration_spec randomizable
  spec/integration_spec.rb
  spec/support/active_record_classes.rb
Labels: maintenance
