Repository meilisearch/meilisearch-rails, pull requests merged in 2025-05, with the labels that each got.

#414 Remove legacy code in specs
  .gitignore
  spec/spec_helper.rb
  spec/support/active_record_schema.rb
  spec/support/sequel_db.rb
Labels: skip-changelog, maintenance

#408 Speed up tests
  spec/model_methods_spec.rb
  spec/ms_clean_up_job_spec.rb
  spec/safe_index_spec.rb
  spec/support/models/animals.rb
  spec/support/models/book.rb
  spec/support/models/color.rb
  spec/support/models/movie.rb
  spec/support/models/people.rb
Labels: maintenance

#419 Bump meilisearch ruby to v0.32 & other small improvements
  .code-samples.meilisearch.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  docker-compose.yml
  meilisearch-rails.gemspec
  spec/support/mongo_models/citizen.rb
Labels: breaking-change
